import { TemplateConfig, TemplateLayer, hydrateFormatSlides } from "@/types/template";

// Legacy-shaped seed data (uses `layers` directly on each format).
// We hydrate to the new `slides` shape at module load so consumers only see TemplateConfig.
interface LegacySeedFormat {
  name: string;
  label: string;
  width: number;
  height: number;
  layers: TemplateLayer[];
}
interface LegacySeedTemplate extends Omit<TemplateConfig, "formats"> {
  formats: LegacySeedFormat[];
}

const LEGACY_SEEDS: LegacySeedTemplate[] = [
  {
    id: "summer-promo-001",
    name: "Summer Promo",
    slug: "summer-promo",
    description: "Seasonal promotion template with bold typography and product imagery",
    thumbnail: "/seed/bg-blue.svg",
    formats: [
      // 9:16 Story (1080x1920)
      {
        name: "story",
        label: "Story (9:16)",
        width: 1080,
        height: 1920,
        layers: [
          {
            id: "story-bg",
            name: "Background",
            type: "image",
            left: 0,
            top: 0,
            width: 1080,
            height: 1920,
            src: "/seed/bg-blue.svg",
            linkedBank: "backgrounds",
            editable: true,
            zIndex: 0,
          },
          {
            id: "story-overlay",
            name: "Overlay",
            type: "rect",
            left: 0,
            top: 1200,
            width: 1080,
            height: 720,
            backgroundColor: "#000000",
            opacity: 0.45,
            zIndex: 1,
          },
          {
            id: "story-product",
            name: "Product Image",
            type: "image",
            left: 240,
            top: 400,
            width: 600,
            height: 600,
            src: "/seed/product-a.svg",
            linkedBank: "products",
            editable: true,
            zIndex: 2,
          },
          {
            id: "story-headline",
            name: "Headline",
            type: "text",
            left: 60,
            top: 1280,
            width: 960,
            height: 160,
            text: "SUMMER SALE",
            fontSize: 96,
            fontFamily: "Arial",
            fontWeight: "bold",
            fill: "#ffffff",
            textAlign: "center",
            linkedBank: "headlines",
            editable: true,
            zIndex: 3,
          },
          {
            id: "story-subtext",
            name: "Subtext",
            type: "text",
            left: 60,
            top: 1460,
            width: 960,
            height: 120,
            text: "Up to 50% off all items",
            fontSize: 48,
            fontFamily: "Arial",
            fontWeight: "normal",
            fill: "#e5e7eb",
            textAlign: "center",
            linkedBank: "subtexts",
            editable: true,
            zIndex: 4,
          },
          {
            id: "story-logo",
            name: "Logo",
            type: "image",
            left: 390,
            top: 1720,
            width: 300,
            height: 100,
            src: "/seed/logo.svg",
            zIndex: 5,
          },
        ],
      },
      // 4:5 Feed (1080x1350)
      {
        name: "feed",
        label: "Feed (4:5)",
        width: 1080,
        height: 1350,
        layers: [
          {
            id: "feed-bg",
            name: "Background",
            type: "image",
            left: 0,
            top: 0,
            width: 1080,
            height: 1350,
            src: "/seed/bg-blue.svg",
            linkedBank: "backgrounds",
            editable: true,
            zIndex: 0,
          },
          {
            id: "feed-overlay",
            name: "Overlay",
            type: "rect",
            left: 0,
            top: 850,
            width: 1080,
            height: 500,
            backgroundColor: "#000000",
            opacity: 0.45,
            zIndex: 1,
          },
          {
            id: "feed-product",
            name: "Product Image",
            type: "image",
            left: 240,
            top: 120,
            width: 600,
            height: 600,
            src: "/seed/product-a.svg",
            linkedBank: "products",
            editable: true,
            zIndex: 2,
          },
          {
            id: "feed-headline",
            name: "Headline",
            type: "text",
            left: 60,
            top: 900,
            width: 960,
            height: 140,
            text: "SUMMER SALE",
            fontSize: 88,
            fontFamily: "Arial",
            fontWeight: "bold",
            fill: "#ffffff",
            textAlign: "center",
            linkedBank: "headlines",
            editable: true,
            zIndex: 3,
          },
          {
            id: "feed-subtext",
            name: "Subtext",
            type: "text",
            left: 60,
            top: 1060,
            width: 960,
            height: 100,
            text: "Up to 50% off all items",
            fontSize: 44,
            fontFamily: "Arial",
            fontWeight: "normal",
            fill: "#e5e7eb",
            textAlign: "center",
            linkedBank: "subtexts",
            editable: true,
            zIndex: 4,
          },
          {
            id: "feed-logo",
            name: "Logo",
            type: "image",
            left: 390,
            top: 1200,
            width: 300,
            height: 100,
            src: "/seed/logo.svg",
            zIndex: 5,
          },
        ],
      },
      // 1:1 Square (1080x1080)
      {
        name: "square",
        label: "Square (1:1)",
        width: 1080,
        height: 1080,
        layers: [
          {
            id: "square-bg",
            name: "Background",
            type: "image",
            left: 0,
            top: 0,
            width: 1080,
            height: 1080,
            src: "/seed/bg-blue.svg",
            linkedBank: "backgrounds",
            editable: true,
            zIndex: 0,
          },
          {
            id: "square-overlay",
            name: "Overlay",
            type: "rect",
            left: 0,
            top: 600,
            width: 1080,
            height: 480,
            backgroundColor: "#000000",
            opacity: 0.45,
            zIndex: 1,
          },
          {
            id: "square-product",
            name: "Product Image",
            type: "image",
            left: 290,
            top: 60,
            width: 500,
            height: 500,
            src: "/seed/product-a.svg",
            linkedBank: "products",
            editable: true,
            zIndex: 2,
          },
          {
            id: "square-headline",
            name: "Headline",
            type: "text",
            left: 60,
            top: 650,
            width: 960,
            height: 120,
            text: "SUMMER SALE",
            fontSize: 80,
            fontFamily: "Arial",
            fontWeight: "bold",
            fill: "#ffffff",
            textAlign: "center",
            linkedBank: "headlines",
            editable: true,
            zIndex: 3,
          },
          {
            id: "square-subtext",
            name: "Subtext",
            type: "text",
            left: 60,
            top: 790,
            width: 960,
            height: 100,
            text: "Up to 50% off all items",
            fontSize: 40,
            fontFamily: "Arial",
            fontWeight: "normal",
            fill: "#e5e7eb",
            textAlign: "center",
            linkedBank: "subtexts",
            editable: true,
            zIndex: 4,
          },
          {
            id: "square-logo",
            name: "Logo",
            type: "image",
            left: 390,
            top: 930,
            width: 300,
            height: 100,
            src: "/seed/logo.svg",
            zIndex: 5,
          },
        ],
      },
    ],
    assetBanks: [
      {
        id: "bank-backgrounds",
        name: "backgrounds",
        type: "image",
        items: [
          { id: "bg-1", label: "Blue", value: "/seed/bg-blue.svg" },
          { id: "bg-2", label: "Green", value: "/seed/bg-green.svg" },
          { id: "bg-3", label: "Orange", value: "/seed/bg-orange.svg" },
        ],
      },
      {
        id: "bank-products",
        name: "products",
        type: "image",
        items: [
          { id: "prod-1", label: "Product A", value: "/seed/product-a.svg" },
          { id: "prod-2", label: "Product B", value: "/seed/product-b.svg" },
          { id: "prod-3", label: "Product C", value: "/seed/product-c.svg" },
        ],
      },
      {
        id: "bank-headlines",
        name: "headlines",
        type: "text",
        items: [
          { id: "hl-1", label: "Summer Sale", value: "SUMMER SALE" },
          { id: "hl-2", label: "Hot Deals", value: "HOT DEALS" },
          { id: "hl-3", label: "Limited Time", value: "LIMITED TIME" },
          { id: "hl-4", label: "Big Savings", value: "BIG SAVINGS" },
        ],
      },
      {
        id: "bank-subtexts",
        name: "subtexts",
        type: "text",
        items: [
          { id: "st-1", label: "50% off", value: "Up to 50% off all items" },
          { id: "st-2", label: "This weekend", value: "This weekend only — don't miss out" },
          { id: "st-3", label: "Shop now", value: "Shop now and save big" },
          { id: "st-4", label: "Ends soon", value: "Hurry — offer ends Sunday" },
        ],
      },
    ],
  },
];

export const SEED_TEMPLATES: TemplateConfig[] = LEGACY_SEEDS.map((t) => ({
  ...t,
  formats: t.formats.map(hydrateFormatSlides),
}));

export function getTemplateBySlug(slug: string): TemplateConfig | undefined {
  return SEED_TEMPLATES.find((t) => t.slug === slug);
}

export function getTemplateById(id: string): TemplateConfig | undefined {
  return SEED_TEMPLATES.find((t) => t.id === id);
}
